name: 'Release Tag'
description: 'Create a release on tag push'
inputs:
  tag_name:
    description: 'The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag'
    required: true
  release_name:
    description: 'The name of the release. For example, `Release v1.0.1`'
    required: false
  body:
    description: 'Text describing the contents of the tag.'
    required: false
  draft:
    description: '`true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`'
    required: false
    default: false
  prerelease:
    description: '`true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`'
    required: false
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'
